### PR TITLE
Implement hardware buttons

### LINKED ISSUE #1: Support for hw bottons.
Hello.

I like your app for wear os. I use it for badminton. However I really miss support for hw buttons. I have Fossil gen 5 and it woud be great if top button woud app point to one player and bottom one for another. 
Do you think its possible to add it? I dont know how to code but ill buy pro version if there will be any with this feature.

Thx for your answer.  :) 

https://developer.android.com/training/wearables/user-input/physical-buttons#kotlin

### PR DESCRIPTION
**Pull request by hegocre**
This needs testing, I'm not sure it works
Closes #1

### CODE REVIEW

**Comment by Barthy727** [comment]
Hi!

I installed wear apk on my Fossil gen 5  trough app called Wear Installer (I uninstalled official app downloaded from store before. Just to make sure it won't interfere) and it work brilliant. Top button add point to left player and bottom one to right player. It even work perfectly when screen is off or it's in always on mode (with amoled). Because before to add point I had to tap screen once for waking it up and then second time to add point. Now I can just tap hw button once. Also when I exit up to start workout on Google Fit or other and I come back to ScoreCounter it did not reset itself.

Great work @hegocre! Nailed it!

**Comment by hegocre** [comment]
@Barthy727 That's nice!

Could you also try double-clicking and long-pressing? They should decrease the counter and reset it to 0.

Thanks!

**Comment by Barthy727** [comment]
Hi.

I tried it and it doesn't work. Double clicking just add 2 points. No matter how fast I try to double click it just add points quickly. And long press doesn't seem to do anything it and point on start of click and then no matter how long I hold it, nothing happens.

**Comment by Barthy727** [comment]
But I think double click can be little misleading. I can imagine someone would want add 2 point, so he will just double click and then he can end up with incorrect score. But long press is good idea.
Just my opinion ofc.

**Comment by hegocre** [comment]
Thanks again for your help!

I removed double-press as it could be misleading, like you said.

Also tried to fix long-press, works on the emulator sending events trough adb, but I'm not sure it'll work on real devices. In case it works, do you think it would be better long-press to decrease score or to set it back to 0 (as it does now)?

Thanks!

**Comment by Barthy727** [comment]
Hi. 
So i tested it and long press for set score to 0 works now. All other functions works as well.

I was thinking that if people want to use this for sports, at end of every set there is an enough time for player to tap watch on display and long press scores. But this depends on how much do you miss add point. But i don't think this happens too much in any sport. Usually its pretty clear who gets point. For example in my case I rarely need to decrease score. I can imagine that long press over 2 sec would reset score to 0 but long press below 2 sec will decrease score. However, can be little confusing for some people. (So sorry I don't have clear answer but I like it as it is now :). )

But there is something I realized. There is no haptic feedback then you add point trough hw button. It would be really great if watch would vibrate when you add point. Just like when you long press screen for set score to 0. Just little stronger or little longer. Like 130% of that when you long press screen. Otherwise, I found myself checking watch frequently to make sure I added point. In ideal, I would like to just press button and don't even look to screen. 

Then I have some other ideas (mainly stoled form this app [https://play.google.com/store/apps/details?id=com.pumpkintechlabs.tenniscoreboardwear](url) ) but I don't know how much you use app yourself or how much time you want to invest to it. However, with Wear OS 3 and a lot more money and development in Wear OS from Google and Samsung, there is chance a lot more Wear OS watches will come out in future and more and more people will use it. :) 

Thank you!

**Comment by hegocre** [comment]
Hi!

I Implemented vibration, should work nice. I'm gonna let the button press behavior as it is now, since the most used one will be the single press to increase the score.

About the features on the app you posted, I don't think I'm gonna implement them, as the idea of this app form the beginning was to made it dead simple for casual and personal use, and just uploaded it to Play Store to download it fast.

Anyway, thank you again!

**Comment by Barthy727** [comment]
Thank you!

I totally understand. Thank you for implementing this! 

Good luck with your next projects.

**Pull request merged**
